// Vite config overrides for the Medusa admin dev server.
//
// Imported by medusa-config.ts (via a runtime patch in docker-entrypoint.sh)
// and returned as the `admin.vite` function.  Medusa's admin-bundler calls
// this function with the base Vite config and uses the return value.
//
// Fixes applied (in order):
//
//   (A) allowedHosts=true / host=true
//       Accept any Host header + listen on 0.0.0.0 so the admin dev server
//       works behind a reverse proxy without 403 "Blocked request".
//
//   (B) server.fs.strict=false + explicit /app/medusa entries in fs.allow
//       Disable Vite's fs strict mode so the i18n virtual module's absolute-
//       path imports are not rejected at serve-time.
//
//   (C) server.hmr = { port: 9001, clientPort: "", path: "/vite-hmr" }
//       Pin the HMR WebSocket to a FIXED container port (default middlewareMode
//       picks a random port that the reverse proxy can't forward).  clientPort=""
//       makes @vite/client fall back to location.port (the proxy HTTPS port the
//       browser actually visits).  path="/vite-hmr" lets the in-container
//       shared-port-proxy.ts route WS Upgrade /vite-hmr(*) to :9001.
//
//   (D) resolve-abs-fs-paths plugin (enforce: "pre")
//       ROOT CAUSE FIX.  The i18n virtual module generated by
//       @medusajs/admin-vite-plugin emits:
//         import i18nTranslations0 from "/app/medusa/src/admin/i18n/index.ts"
//       Vite's base="/app/" causes resolveId to STRIP the base prefix from
//       leading-"/" imports, leaving "/medusa/src/admin/i18n/index.ts" which
//       does NOT exist on disk → "Failed to resolve import ... Does the file
//       exist?" → admin page renders blank (JS module served as text/html
//       fallback).
//       This pre-plugin intercepts leading-"/" imports BEFORE Vite's base
//       stripping, checks if the ORIGINAL path exists on disk, and returns
//       it directly — bypassing the broken resolution.

const adminVite = (config: any): any => {
  config.server = config.server || {};

  // (A)
  config.server.allowedHosts = true;
  config.server.host = true;

  // (B)
  config.server.fs = config.server.fs || {};
  config.server.fs.strict = false;
  config.server.fs.allow = [
    ...((config.server.fs.allow as string[]) || []),
    "/app/medusa",
    "/app/medusa/src",
  ];

  // (C)
  config.server.hmr = { port: 9001, clientPort: "", path: "/vite-hmr" };

  // (D)
  config.plugins = [
    ...(config.plugins || []),
    {
      name: "resolve-abs-fs-paths",
      enforce: "pre",
      resolveId(source: string) {
        if (
          typeof source === "string" &&
          source.startsWith("/") &&
          !source.startsWith("//")
        ) {
          try {
            // Bun supports require() in ESM — Vite plugins run in the same
            // process as the config, so this works under `bun run dev`.
            // eslint-disable-next-line @typescript-eslint/no-require-imports
            const fs = require("node:fs");
            if (fs.existsSync(source) && fs.statSync(source).isFile()) {
              return source;
            }
          } catch {
            // require unavailable or fs error — fall through to Vite's resolve
          }
        }
        return null;
      },
    },
  ];

  return config;
};

export default adminVite;
