#!/bin/sh
# ---------------------------------------------------------------------------
# Development entrypoint (Bun-only, no Node.js).
#
#   1. First boot: seed the empty bind-mount with the starter source code
#      baked into the image (so `./medusa-app` is populated automatically).
#   2. Install dependencies if node_modules is missing.
#   3. Patch @jridgewell/trace-mapping to clamp -1 columns to 0, working
#      around Bun bug #17303 (source-map-support crash in containers).
#   4. Generate a .env file from environment variables (if absent).
#   5. Append sslmode=disable&connect_timeout=30 to DATABASE_URL.
#   6. Run database migrations (creates tables required by medusa develop).
#   7. Optionally create the admin user.
#   8. Hand off to `bun run dev` (i.e. `medusa develop`).
# ---------------------------------------------------------------------------
set -eu

APP_DIR="/app/medusa"
SEED_DIR="/app/medusa-seed"

# --- (1) Seed source code on first boot -----------------------------------
# Check for package.json rather than "is the dir empty" — the named volume
# mounted at node_modules makes the dir appear non-empty even on first boot.
if [ ! -f "$APP_DIR/package.json" ]; then
  echo "[dev-entrypoint] First boot: seeding source code into $APP_DIR ..."
  cp -a "$SEED_DIR/." "$APP_DIR/"
  echo "[dev-entrypoint] Source code seeded. You can now edit files in ./medusa-app/ on the host."
fi

cd "$APP_DIR"

# --- (2) Install dependencies if missing ----------------------------------
if [ ! -d "$APP_DIR/node_modules" ] || [ -z "$(ls -A "$APP_DIR/node_modules" 2>/dev/null)" ]; then
  echo "[dev-entrypoint] node_modules missing — running bun install (first boot, may take a while) ..."
  bun install
  echo "[dev-entrypoint] Dependencies installed."
fi

# --- (3) Patch trace-mapping for Bun compatibility (#17303) ---------------
# Bun's runtime can produce -1 column values in stack traces; trace-mapping
# throws on negative columns, crashing medusa develop.  Replace the throw
# (or any previous broken replacement that writes to undefined variables)
# with a safe `return {source:null,line:null,column:null,name:null}`.
#
# NOTE: Previous iterations of this entrypoint accidentally replaced the
# COL_GTR_EQ_ZERO throw with `aNeedle[aColumnName]=0`, referencing undefined
# variables that caused a ReferenceError.  The logic here is therefore:
#   a) Revert any stale `aNeedle[aColumnName]=0` back to the original throw.
#   b) Apply the correct null-return patch to both throw sites.
# Running (a)+(b) every boot makes the patch idempotent regardless of the
# prior state of the file (fresh / partially patched / broken).
_patch_trace_mapping() {
  _file="$1"
  [ -f "$_file" ] || return 0
  # (a) revert the broken aNeedle replacement back to the throw
  if grep -q 'aNeedle\[aColumnName\]=0' "$_file" 2>/dev/null; then
    sed -i 's/aNeedle\[aColumnName\]=0/throw new Error(COL_GTR_EQ_ZERO)/g' "$_file"
  fi
  # (b) now always re-apply the correct null-return patch for both throw sites
  if grep -q 'throw new Error(COL_GTR_EQ_ZERO)\|throw new Error(LINE_GTR_ZERO)' "$_file" 2>/dev/null; then
    echo "[dev-entrypoint] Patching $_file (Bun #17303 workaround)..."
    sed -i 's/throw new Error(COL_GTR_EQ_ZERO)/return {source:null,line:null,column:null,name:null}/g' "$_file"
    sed -i 's/throw new Error(LINE_GTR_ZERO)/return {source:null,line:null,column:null,name:null}/g' "$_file"
  fi
}
_patch_trace_mapping "$APP_DIR/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js"
# Also patch the source-map-support copy if it bundles its own trace-mapping
for tm in "$APP_DIR"/node_modules/@cspotcode/source-map-support/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js; do
  _patch_trace_mapping "$tm"
done

# --- (4) Generate .env from environment variables (if absent) -------------
if [ ! -f "$APP_DIR/.env" ]; then
  echo "[dev-entrypoint] Generating .env from environment variables ..."
  cat > "$APP_DIR/.env" <<EOF
# Auto-generated by docker-entrypoint-dev.sh on first boot.
# Edit freely — this file is NOT managed after creation.
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=${REDIS_URL:-}
JWT_SECRET=${JWT_SECRET:-change_me_jwt}
COOKIE_SECRET=${COOKIE_SECRET:-change_me_cookie}
STORE_CORS=${STORE_CORS:-http://localhost:8000}
ADMIN_CORS=${ADMIN_CORS:-http://localhost:5173,http://localhost:9000}
AUTH_CORS=${AUTH_CORS:-http://localhost:5173,http://localhost:8000,http://localhost:9000}
EOF
  echo "[dev-entrypoint] .env created."
fi

# --- (5) Normalise DATABASE_URL -------------------------------------------
if [ -n "${DATABASE_URL:-}" ]; then
  case "$DATABASE_URL" in
    *sslmode=*)    : ;;
    *\?*)          DATABASE_URL="${DATABASE_URL}&sslmode=disable&connect_timeout=30" ;;
    *)             DATABASE_URL="${DATABASE_URL}?sslmode=disable&connect_timeout=30" ;;
  esac
  export DATABASE_URL
  if grep -q '^DATABASE_URL=' "$APP_DIR/.env" 2>/dev/null; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DATABASE_URL|" "$APP_DIR/.env"
  fi
fi

# --- (6) Run database migrations ------------------------------------------
# `medusa develop` loads module loaders (Tax, Currency, Region...) that
# query the DB at boot; if tables don't exist the boot fails fatally with
# "relation ... does not exist".  Run migrations first, mirroring the
# production entrypoint.  Use `bun run migrate` (not bunx) to avoid CJS/ESM
# parsing issues in Medusa's config loader.
echo "[dev-entrypoint] Running database migrations ..."
if ! MIGRATE_LOG=$(bun run migrate 2>&1); then
  echo "$MIGRATE_LOG"
  echo "[dev-entrypoint] Migration failed — retrying once in 5s ..."
  sleep 5
  if ! MIGRATE_LOG=$(bun run migrate 2>&1); then
    echo "$MIGRATE_LOG"
    echo "[dev-entrypoint] Migration retried and failed — dev server may crash if tables are missing."
  else
    echo "[dev-entrypoint] Retry succeeded.  Database migrations complete."
  fi
else
  echo "$MIGRATE_LOG"
  echo "[dev-entrypoint] Database migrations complete."
fi

# --- (7) Auto-create admin user (optional) --------------------------------
ADMIN_EMAIL="${MEDUSA_ADMIN_EMAIL:-}"
ADMIN_PASSWORD="${MEDUSA_ADMIN_PASSWORD:-}"
if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
  echo "[dev-entrypoint] Ensuring admin user '$ADMIN_EMAIL' exists ..."
  # `bun run create-admin` resolves modules via bun run (avoids bunx CJS/ESM
  # conflict).  $MEDUSA_ADMIN_EMAIL / $MEDUSA_ADMIN_PASSWORD are expanded at
  # runtime by the shell from the script string baked into package.json.
  if MEDUSA_ADMIN_EMAIL="$ADMIN_EMAIL" MEDUSA_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
       bun run create-admin 2>&1; then
    echo "[dev-entrypoint] Admin user created."
  else
    echo "[dev-entrypoint] Admin user already exists — skipping."
  fi
fi

# --- (8) Hand off to dev server -------------------------------------------
echo "[dev-entrypoint] Starting dev server: $*"
exec "$@"
