#!/bin/sh
# ---------------------------------------------------------------------------
# Development entrypoint (Bun-only, no Node.js).
#
#   1. First boot: seed the empty bind-mount with the starter source code
#      baked into the image (so `./medusa-app` is populated automatically).
#   2. Install dependencies if node_modules is missing.
#   3. Patch @jridgewell/trace-mapping to clamp -1 columns to 0, working
#      around Bun bug #17303 (source-map-support crash in containers).
#   4. Generate a .env file from environment variables (if absent).
#   5. Append sslmode=disable&connect_timeout=30 to DATABASE_URL.
#   6. Optionally create the admin user.
#   7. Hand off to `bun run dev` (i.e. `medusa develop`).
# ---------------------------------------------------------------------------
set -eu

APP_DIR="/app/medusa"
SEED_DIR="/app/medusa-seed"

# --- (1) Seed source code on first boot -----------------------------------
# Check for package.json rather than "is the dir empty" — the named volume
# mounted at node_modules makes the dir appear non-empty even on first boot.
if [ ! -f "$APP_DIR/package.json" ]; then
  echo "[dev-entrypoint] First boot: seeding source code into $APP_DIR ..."
  cp -a "$SEED_DIR/." "$APP_DIR/"
  echo "[dev-entrypoint] Source code seeded. You can now edit files in ./medusa-app/ on the host."
fi

cd "$APP_DIR"

# --- (2) Install dependencies if missing ----------------------------------
if [ ! -d "$APP_DIR/node_modules" ] || [ -z "$(ls -A "$APP_DIR/node_modules" 2>/dev/null)" ]; then
  echo "[dev-entrypoint] node_modules missing — running bun install (first boot, may take a while) ..."
  bun install
  echo "[dev-entrypoint] Dependencies installed."
fi

# --- (3) Patch trace-mapping for Bun compatibility (#17303) ---------------
# Bun's runtime can produce -1 column values in stack traces; trace-mapping
# throws on negative columns, crashing medusa develop.  Clamp -1 to 0.
TRACE_MAP="$APP_DIR/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js"
if [ -f "$TRACE_MAP" ] && ! grep -q 'aNeedle\[aColumnName\]=0' "$TRACE_MAP" 2>/dev/null; then
  echo "[dev-entrypoint] Patching @jridgewell/trace-mapping (Bun #17303 workaround)..."
  sed -i 's/throw new Error(COL_GTR_EQ_ZERO)/aNeedle[aColumnName]=0/g' "$TRACE_MAP"
fi
# Also patch the source-map-support copy if it bundles its own trace-mapping
for tm in "$APP_DIR"/node_modules/@cspotcode/source-map-support/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js; do
  if [ -f "$tm" ] && ! grep -q 'aNeedle\[aColumnName\]=0' "$tm" 2>/dev/null; then
    sed -i 's/throw new Error(COL_GTR_EQ_ZERO)/aNeedle[aColumnName]=0/g' "$tm"
  fi
done

# --- (4) Generate .env from environment variables (if absent) -------------
if [ ! -f "$APP_DIR/.env" ]; then
  echo "[dev-entrypoint] Generating .env from environment variables ..."
  cat > "$APP_DIR/.env" <<EOF
# Auto-generated by docker-entrypoint-dev.sh on first boot.
# Edit freely — this file is NOT managed after creation.
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=${REDIS_URL:-}
JWT_SECRET=${JWT_SECRET:-change_me_jwt}
COOKIE_SECRET=${COOKIE_SECRET:-change_me_cookie}
STORE_CORS=${STORE_CORS:-http://localhost:8000}
ADMIN_CORS=${ADMIN_CORS:-http://localhost:5173,http://localhost:9000}
AUTH_CORS=${AUTH_CORS:-http://localhost:5173,http://localhost:8000,http://localhost:9000}
EOF
  echo "[dev-entrypoint] .env created."
fi

# --- (5) Normalise DATABASE_URL -------------------------------------------
if [ -n "${DATABASE_URL:-}" ]; then
  case "$DATABASE_URL" in
    *sslmode=*)    : ;;
    *\?*)          DATABASE_URL="${DATABASE_URL}&sslmode=disable&connect_timeout=30" ;;
    *)             DATABASE_URL="${DATABASE_URL}?sslmode=disable&connect_timeout=30" ;;
  esac
  export DATABASE_URL
  if grep -q '^DATABASE_URL=' "$APP_DIR/.env" 2>/dev/null; then
    sed -i "s|^DATABASE_URL=.*|DATABASE_URL=$DATABASE_URL|" "$APP_DIR/.env"
  fi
fi

# --- (6) Auto-create admin user (optional) --------------------------------
ADMIN_EMAIL="${MEDUSA_ADMIN_EMAIL:-}"
ADMIN_PASSWORD="${MEDUSA_ADMIN_PASSWORD:-}"
if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
  echo "[dev-entrypoint] Ensuring admin user '$ADMIN_EMAIL' exists ..."
  if bunx medusa user -e "$ADMIN_EMAIL" -p "$ADMIN_PASSWORD" 2>&1; then
    echo "[dev-entrypoint] Admin user created."
  else
    echo "[dev-entrypoint] Admin user already exists — skipping."
  fi
fi

# --- (7) Hand off to dev server -------------------------------------------
echo "[dev-entrypoint] Starting dev server: $*"
exec "$@"
