#!/bin/sh
# ---------------------------------------------------------------------------
# Production entrypoint (Bun-only, no Node.js, no Vite dev server).
#
# Runtime bootstrap:
#   1. Derive CORS origins + ADMIN_URL from a single $BASE_URL when set.
#   2. Auto-generate missing long-hex secrets (JWT / COOKIE / AUTH_MFA_*)
#      and persist them inside the container so restarts remain stable.
#      User-provided values always take precedence.
#   3. Generate/sync /app/medusa/.env consumed by the built Medusa bundle.
#   4. Normalise DATABASE_URL (sslmode + connect_timeout).
#   5. Run database migrations (`bun run migrate`).
#   6. Ensure the admin user exists (`bun run create-admin`).
#   7. Hand off to CMD — by default: bun run start.
# ---------------------------------------------------------------------------
set -eu

APP_DIR="/app/medusa"
cd "$APP_DIR"

# --- (0) Helpers ------------------------------------------------------------
ensure_env_var() {
  key="$1"; val="$2"
  if [ -f "$APP_DIR/.env" ] && grep -q "^${key}=" "$APP_DIR/.env"; then
    _ENV_TMP="${APP_DIR}/.env.$$"
    awk -v newval="${key}=${val}" '
      BEGIN { replaced = 0 }
      {
        if (!replaced && $0 ~ /^'"$key"'=/) { print newval; replaced = 1 }
        else { print $0 }
      }
      END { if (!replaced) print newval }
    ' "$APP_DIR/.env" > "$_ENV_TMP" && mv "$_ENV_TMP" "$APP_DIR/.env"
    rm -f "$_ENV_TMP"
  else
    echo "${key}=${val}" >> "$APP_DIR/.env"
  fi
}

# --- (1) BASE_URL → derive CORS + ADMIN_URL --------------------------------
if [ -n "${BASE_URL:-}" ]; then
  BASE_URL="${BASE_URL%/}"
  case "$BASE_URL" in
    https://*) _PROTO=https ;;
    http://*)  _PROTO=http  ;;
    *)
      echo "[prod-entrypoint] WARN: BASE_URL='$BASE_URL' missing scheme, assuming http://" >&2
      _PROTO=http
      BASE_URL="http://$BASE_URL"
      ;;
  esac
  _REST="${BASE_URL#*://}"
  _HOSTPORT="${_REST%%/*}"
  case "$_HOSTPORT" in
    *:*) _HOST="${_HOSTPORT%:*}"; _PORT="${_HOSTPORT##*:}" ;;
    *)   _HOST="$_HOSTPORT"
         case "$_PROTO" in https) _PORT=443 ;; *) _PORT=80 ;; esac ;;
  esac
  ORIGIN="$_PROTO://$_HOST:$_PORT"

  LOCAL_STORE="http://localhost:8000"
  LOCAL_ADMIN="http://localhost:5173,http://localhost:9000"

  : "${STORE_CORS:=$ORIGIN,$LOCAL_STORE}"
  : "${ADMIN_CORS:=$ORIGIN,$LOCAL_ADMIN}"
  : "${AUTH_CORS:=$ORIGIN,$LOCAL_ADMIN,$LOCAL_STORE}"
  # Default admin dashboard URL = BASE_URL plus /app subpath.  This gets
  # used by admin-bundler to construct absolute login / post-login redirects.
  : "${ADMIN_URL:=$ORIGIN/app}"

  export STORE_CORS ADMIN_CORS AUTH_CORS ADMIN_URL
fi

# --- (2) Seed / sync .env --------------------------------------------------
if [ ! -f "$APP_DIR/.env" ]; then
  cat > "$APP_DIR/.env" <<EOF
# Auto-generated by docker-entrypoint-prod.sh on first boot.
# Runtime-generated values (CORS, URLs, secrets) are kept stable here.
NODE_ENV=production
DATABASE_URL=${DATABASE_URL:-}
REDIS_URL=${REDIS_URL:-}
EOF
  echo "[prod-entrypoint] .env initialised."
fi

# --- (3) Secrets auto-generation -------------------------------------------
random_hex32() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  else
    od -v -An -N32 -tx2 /dev/urandom 2>/dev/null | tr -d ' \n' || \
    (bun -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))' 2>/dev/null)
  fi
}
is_strong_value() {
  val="$1"
  [ -n "$val" ] || return 1
  [ "${#val}" -ge 64 ] || return 1
  case "$val" in
    change_me*|*placeholder*|*supersecret*) return 1 ;;
  esac
  return 0
}
ensure_secret() {
  key="$1"; label="$2"; minlen="$3"
  # 1) container env wins (user's .env → docker-compose → env var)
  eval current=\"\${${key}:-}\"
  if is_strong_value "$current" 2>/dev/null || ([ -n "$current" ] && [ "${#current}" -ge "$minlen" ]); then
    export "${key}=${current}"
    ensure_env_var "$key" "$current"
    echo "[prod-entrypoint] $label ✓ container env (explicit value used)."
    return 0
  fi
  # 2) previously written .env
  if [ -f "$APP_DIR/.env" ]; then
    from_file="$(sed -n "s/^${key}=//p" "$APP_DIR/.env" 2>/dev/null | tail -n1 || true)"
    if is_strong_value "$from_file" 2>/dev/null || ([ -n "$from_file" ] && [ "${#from_file}" -ge "$minlen" ]); then
      export "${key}=${from_file}"
      echo "[prod-entrypoint] $label ✓ persisted value from $APP_DIR/.env."
      return 0
    fi
  fi
  # 3) generate and persist
  generated="$(random_hex32)"
  if [ "$key" = "AUTH_MFA_ENCRYPTION_KEY" ]; then
    generated="${generated}$(random_hex32)"
  fi
  export "${key}=${generated}"
  ensure_env_var "$key" "$generated"
  echo "[prod-entrypoint] $label ✨ auto-generated (length=${#generated})."
}
ensure_secret JWT_SECRET                 "JWT_SECRET" 64
ensure_secret COOKIE_SECRET              "COOKIE_SECRET" 64
ensure_secret AUTH_MFA_ENCRYPTION_KEY    "AUTH_MFA_ENCRYPTION_KEY" 64

# --- (4) Sync CORS / URL vars to .env --------------------------------------
ensure_env_var STORE_CORS  "${STORE_CORS:-http://localhost:8000}"
ensure_env_var ADMIN_CORS  "${ADMIN_CORS:-http://localhost:5173,http://localhost:9000}"
ensure_env_var AUTH_CORS   "${AUTH_CORS:-http://localhost:5173,http://localhost:8000,http://localhost:9000}"
[ -n "${ADMIN_URL:-}" ] && ensure_env_var ADMIN_URL "$ADMIN_URL"

# --- (5) Normalise DATABASE_URL + REDIS_URL --------------------------------
if [ -n "${DATABASE_URL:-}" ]; then
  case "$DATABASE_URL" in
    *sslmode=*)    : ;;
    *\?*)          DATABASE_URL="${DATABASE_URL}&sslmode=disable&connect_timeout=30" ;;
    *)             DATABASE_URL="${DATABASE_URL}?sslmode=disable&connect_timeout=30" ;;
  esac
  export DATABASE_URL
  ensure_env_var DATABASE_URL "$DATABASE_URL"
fi
[ -n "${REDIS_URL:-}" ] && ensure_env_var REDIS_URL "$REDIS_URL"

# --- (6) Run database migrations ------------------------------------------
if [ "${MEDUSA_AUTO_MIGRATE:-true}" != "false" ]; then
  echo "[prod-entrypoint] Running database migrations ..."
  RETRY=0
  MAX_RETRIES=30
  until bun run migrate 2>&1; do
    RETRY=$((RETRY + 1))
    if [ "$RETRY" -ge "$MAX_RETRIES" ]; then
      echo "[prod-entrypoint] ERROR: bun run migrate failed after $MAX_RETRIES attempts — is Postgres reachable and healthy?"
      exit 1
    fi
    echo "[prod-entrypoint] migrate failed (attempt $RETRY/$MAX_RETRIES), retrying in 2s ..."
    sleep 2
  done
  echo "[prod-entrypoint] Database migrations applied."
else
  echo "[prod-entrypoint] MEDUSA_AUTO_MIGRATE=false — skipping database migrations."
fi

# --- (7) Ensure admin user exists ------------------------------------------
ADMIN_EMAIL="${MEDUSA_ADMIN_EMAIL:-}"
ADMIN_PASSWORD="${MEDUSA_ADMIN_PASSWORD:-}"
if [ -n "$ADMIN_EMAIL" ] && [ -n "$ADMIN_PASSWORD" ]; then
  echo "[prod-entrypoint] Ensuring admin user '$ADMIN_EMAIL' exists ..."
  if MEDUSA_ADMIN_EMAIL="$ADMIN_EMAIL" MEDUSA_ADMIN_PASSWORD="$ADMIN_PASSWORD" \
       bun run create-admin 2>&1; then
    echo "[prod-entrypoint] Admin user created."
  else
    echo "[prod-entrypoint] Admin user already exists — skipping."
  fi
fi

# --- (8) Hand off to CMD ----------------------------------------------------
echo "[prod-entrypoint] Starting production server: $*"
exec "$@"
